2025-02-12 02:40:14,412 - root - INFO - ü§ñ –ò–Ω–∏—Ü–∏–∞–ª–∏–∑–∞—Ü–∏—è –±–æ—Ç–∞...
2025-02-12 02:40:14,412 - root - INFO - Bot token status: PRESENT
2025-02-12 02:40:14,413 - root - INFO - Telegram Bot starting...
2025-02-12 02:40:15,328 - root - INFO - ‚úÖ –ü—Ä–∏–ª–æ–∂–µ–Ω–∏–µ —Å–æ–∑–¥–∞–Ω–æ —Å —Ç–æ–∫–µ–Ω–æ–º: 7679123098...
2025-02-12 02:40:15,329 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-02-12 02:40:15,330 - root - INFO - ‚úÖ –î–∂–æ–± –¥–ª—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –º–µ–º–æ–≤ –Ω–∞—Å—Ç—Ä–æ–µ–Ω —É—Å–ø–µ—à–Ω–æ
2025-02-12 02:40:15,330 - root - INFO - üöÄ –ù–∞—á–∞–ª–æ polling...
2025-02-12 02:40:15,330 - asyncio - DEBUG - Using proactor: IocpProactor
2025-02-12 02:40:17,354 - apscheduler.scheduler - INFO - Added job "send_meme" to job store "default"
2025-02-12 02:40:17,354 - apscheduler.scheduler - INFO - Scheduler started
2025-02-12 02:40:17,354 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2025-02-12 02:40:17,354 - apscheduler.scheduler - DEBUG - Next wakeup is due at 2025-02-11 21:40:25.328960+00:00 (in 7.974106 seconds)
2025-02-12 02:40:22,150 - root - ERROR - –ù–µ–∏–∑–≤–µ—Å—Ç–Ω–∞—è –æ—à–∏–±–∫–∞: httpx.ReadError: 
Traceback (most recent call last):
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\http11.py", line 136, in handle_async_request
    raise exc
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\http11.py", line 106, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_async\http11.py", line 217, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.READ_NUM_BYTES, timeout=timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_httpxrequest.py", line 293, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\nsdape\telegrammbot\bot.py", line 51, in error_handler
    raise context.error
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 750, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 744, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 371, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 650, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4480, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 619, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 354, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 648, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 334, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Sp1Dpwnz\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_httpxrequest.py", line 317, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ReadError: 
2025-02-12 02:40:25,332 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2025-02-12 02:40:25,332 - apscheduler.scheduler - INFO - Removed job c734d2d64cdb457f9cc5b79c39b8664a
2025-02-12 02:40:25,333 - apscheduler.scheduler - DEBUG - No jobs; waiting until a job is added
2025-02-12 02:40:25,333 - apscheduler.executors.default - INFO - Running job "send_meme (trigger: date[2025-02-11 21:40:25 UTC], next run at: 2025-02-11 21:40:25 UTC)" (scheduled at 2025-02-11 21:40:25.328960+00:00)
2025-02-12 02:40:25,333 - root - INFO - üïí –ó–∞–ø—É—Å–∫ send_meme_callback –¥–ª—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –º–µ–º–∞
2025-02-12 02:40:25,333 - root - INFO - üöÄ –ù–∞—á–∞–ª–æ –ø—Ä–æ—Ü–µ—Å—Å–∞ –æ—Ç–ø—Ä–∞–≤–∫–∏ –º–µ–º–∞
2025-02-12 02:40:25,745 - root - INFO - –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –∫–∞–Ω–∞–ª–µ: ChatFullInfo(accent_color_id=5, active_usernames=('Sp1DShiz',), api_kwargs={'can_send_gift': True}, can_send_paid_media=True, description='Not SABE Person \nNot SANE Person\nSad Pain 1 more Depression', has_protected_content=True, has_visible_history=True, id=-1002394808904, invite_link='https://t.me/+I4ROzSsdl7M5ZTMy', linked_chat_id=-1002494962209, max_reaction_count=11, photo=ChatPhoto(big_file_id='AQADAgADH-AxG3VvuUkACAMAA7gNnZwW____N9lGK-xXuhQ2BA', big_file_unique_id='AQADH-AxG3VvuUkB', small_file_id='AQADAgADH-AxG3VvuUkACAIAA7gNnZwW____N9lGK-xXuhQ2BA', small_file_unique_id='AQADH-AxG3VvuUkAAQ'), pinned_message=Message(channel_chat_created=False, chat=Chat(id=-1002394808904, title='—à–∏–∑–∞', type=<ChatType.CHANNEL>, username='Sp1DShiz'), date=datetime.datetime(2024, 11, 14, 9, 47, 23, tzinfo=datetime.timezone.utc), delete_chat_photo=False, edit_date=datetime.datetime(2024, 11, 15, 18, 21, 48, tzinfo=datetime.timezone.utc), group_chat_created=False, has_protected_content=True, message_id=3, sender_chat=Chat(id=-1002394808904, title='—à–∏–∑–∞', type=<ChatType.CHANNEL>, username='Sp1DShiz'), supergroup_chat_created=False, text='–ù—É –∞ —Ö—É–ª–∏ —É –≤—Å–µ—Ö –µ—Å—Ç—å –∏ —É –º–µ–Ω—è –±—É–¥–µ—Ç —Ç–æ–ª—å–∫–æ —Ö—É–π —è —á–µ –≤—ã–∫–ª–∞–¥—ã–≤–∞—Ç—å –±—É–¥—É'), title='—à–∏–∑–∞', type=<ChatType.CHANNEL>, username='Sp1DShiz')
2025-02-12 02:40:25,745 - root - INFO - üöÄ –ù–∞—á–∞–ª–æ –ø—Ä–æ—Ü–µ—Å—Å–∞ –ø–æ–ª—É—á–µ–Ω–∏—è –º–µ–º–∞
2025-02-12 02:40:26,216 - root - INFO - ‚úÖ –£—Å–ø–µ—à–Ω–æ–µ SSL-—Å–æ–µ–¥–∏–Ω–µ–Ω–∏–µ —Å Reddit
2025-02-12 02:40:26,219 - root - INFO - Reddit Client ID: 1f0se...
2025-02-12 02:40:26,219 - root - INFO - Reddit Client Secret: **********
2025-02-12 02:40:26,219 - root - INFO - Reddit User Agent: python:telegram_reddit_bot:1.0 (by /u/major_sh1za)
2025-02-12 02:40:26,220 - root - INFO - –°–ø–∏—Å–æ–∫ —Å—É–±-—Ä–µ–¥–¥–∏—Ç–æ–≤ –¥–ª—è –ø–æ–∏—Å–∫–∞: ['memes', 'dankmemes', 'funny', 'ru_memes', 'Pikabu']
2025-02-12 02:40:26,221 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/memes/hot at 1739310026.221309
2025-02-12 02:40:26,221 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:26,222 - asyncprawcore - DEBUG - Params: {'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:28,456 - asyncprawcore - DEBUG - Response: 200 (52208 bytes) (rst-572:rem-999.0:used-1 ratelimit) at 1739310028.4561343
2025-02-12 02:40:28,577 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/memes/hot at 1739310028.5771325
2025-02-12 02:40:28,577 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:28,577 - asyncprawcore - DEBUG - Params: {'after': 't3_1im4ped', 'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:30,225 - asyncprawcore - DEBUG - Response: 200 (48696 bytes) (rst-570:rem-998.0:used-2 ratelimit) at 1739310030.2250109
2025-02-12 02:40:30,327 - root - INFO - –ü–æ–ª—É—á–µ–Ω–æ 192 –º–µ–º–æ–≤ –∏–∑ memes
2025-02-12 02:40:30,328 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/dankmemes/hot at 1739310030.3282347
2025-02-12 02:40:30,328 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:30,328 - asyncprawcore - DEBUG - Params: {'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:31,585 - asyncprawcore - DEBUG - Response: 200 (57983 bytes) (rst-569:rem-997.0:used-3 ratelimit) at 1739310031.5859337
2025-02-12 02:40:31,716 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/dankmemes/hot at 1739310031.716135
2025-02-12 02:40:31,716 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:31,717 - asyncprawcore - DEBUG - Params: {'after': 't3_1iltyac', 'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:33,002 - asyncprawcore - DEBUG - Response: 200 (58835 bytes) (rst-567:rem-996.0:used-4 ratelimit) at 1739310033.0028427
2025-02-12 02:40:33,132 - root - INFO - –ü–æ–ª—É—á–µ–Ω–æ 198 –º–µ–º–æ–≤ –∏–∑ dankmemes
2025-02-12 02:40:33,132 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/funny/hot at 1739310033.132868
2025-02-12 02:40:33,133 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:33,133 - asyncprawcore - DEBUG - Params: {'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:34,619 - asyncprawcore - DEBUG - Response: 200 (69766 bytes) (rst-566:rem-995.0:used-5 ratelimit) at 1739310034.619903
2025-02-12 02:40:34,650 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/funny/hot at 1739310034.6500366
2025-02-12 02:40:34,650 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:34,650 - asyncprawcore - DEBUG - Params: {'after': 't3_1imnf0s', 'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:37,023 - asyncprawcore - DEBUG - Response: 200 (67258 bytes) (rst-564:rem-994.0:used-6 ratelimit) at 1739310037.023936
2025-02-12 02:40:37,053 - root - INFO - –ü–æ–ª—É—á–µ–Ω–æ 110 –º–µ–º–æ–≤ –∏–∑ funny
2025-02-12 02:40:37,053 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/ru_memes/hot at 1739310037.0539272
2025-02-12 02:40:37,054 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:37,054 - asyncprawcore - DEBUG - Params: {'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:37,505 - asyncprawcore - DEBUG - Response: 200 (9120 bytes) (rst-562:rem-993.0:used-7 ratelimit) at 1739310037.5050745
2025-02-12 02:40:37,507 - root - INFO - –ü–æ–ª—É—á–µ–Ω–æ 17 –º–µ–º–æ–≤ –∏–∑ ru_memes
2025-02-12 02:40:37,508 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/Pikabu/hot at 1739310037.508132
2025-02-12 02:40:37,508 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:37,508 - asyncprawcore - DEBUG - Params: {'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:40,544 - asyncprawcore - DEBUG - Response: 200 (115023 bytes) (rst-562:rem-992.0:used-8 ratelimit) at 1739310040.544757
2025-02-12 02:40:40,690 - asyncprawcore - DEBUG - Fetching: GET https://oauth.reddit.com/r/Pikabu/hot at 1739310040.690728
2025-02-12 02:40:40,691 - asyncprawcore - DEBUG - Data: None
2025-02-12 02:40:40,691 - asyncprawcore - DEBUG - Params: {'after': 't3_1ilf96c', 'limit': '200', 'raw_json': '1'}
2025-02-12 02:40:43,424 - asyncprawcore - DEBUG - Response: 200 (132703 bytes) (rst-558:rem-991.0:used-9 ratelimit) at 1739310043.424893
2025-02-12 02:40:43,646 - root - INFO - –ü–æ–ª—É—á–µ–Ω–æ 83 –º–µ–º–æ–≤ –∏–∑ Pikabu
2025-02-12 02:40:43,647 - root - INFO - –í—Å–µ–≥–æ —Å–æ–±—Ä–∞–Ω–æ –º–µ–º–æ–≤: 600
2025-02-12 02:40:43,648 - root - INFO - –ù–∞–π–¥–µ–Ω–æ –≤–∞–ª–∏–¥–Ω—ã—Ö –º–µ–º–æ–≤: 600
2025-02-12 02:40:43,651 - root - INFO - ‚úÖ –í—ã–±—Ä–∞–Ω –º–µ–º: me whenever I have a crisis –∏–∑ memes
2025-02-12 02:40:43,652 - root - INFO - üì∏ –ü–æ–ø—ã—Ç–∫–∞ –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –º–µ–º –≤ –∫–∞–Ω–∞–ª: @Sp1DShiz
2025-02-12 02:40:43,653 - root - INFO - üîó URL –º–µ–º–∞: https://i.redd.it/qu2gqrlgwdie1.jpeg
2025-02-12 02:40:44,474 - root - INFO - ‚úÖ –ú–µ–º —É—Å–ø–µ—à–Ω–æ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω –∏–∑ memes
2025-02-12 02:40:44,474 - apscheduler.scheduler - INFO - Added job "send_meme" to job store "default"
2025-02-12 02:40:44,476 - root - INFO - ‚è∞ –°–ª–µ–¥—É—é—â–∏–π –º–µ–º –±—É–¥–µ—Ç –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω —á–µ—Ä–µ–∑ 2.8 —á–∞—Å–æ–≤
2025-02-12 02:40:44,478 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2025-02-12 02:40:44,479 - apscheduler.scheduler - DEBUG - Next wakeup is due at 2025-02-12 00:25:49.532705+00:00 (in 9905.053365 seconds)
2025-02-12 02:40:44,481 - apscheduler.executors.default - INFO - Job "send_meme (trigger: date[2025-02-11 21:40:25 UTC], next run at: 2025-02-11 21:40:25 UTC)" executed successfully
